---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-hpa
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/soft-titus/hello^1.x
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/app.allow-tags: "^[1-9]+\\.[0-9]+\\.[0-9]+$"
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/app.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/env/heterodon/hello-hpa/values.yaml
spec:
  project: hello
  source:
    repoURL: git@github.com:soft-titus/argocd-apps.git
    path: "env/heterodon/hello-hpa"
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-hpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
