---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-hpa
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/soft-titus/hello
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/app.allow-tags: ">=1.0.0 <2.0.0"
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-credential-secrets
    argocd-image-updater.argoproj.io/git-repository: git@github.com:soft-titus/argocd-apps
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-path: env/heterodon/hello-hpa.yaml
spec:
  project: hello
  source:
    repoURL: https://soft-titus.github.io/titus-charts
    chart: microservice
    targetRevision: "0.*"
    helm:
      values: |
        fullnameOverride: "hello-hpa"
        image:
          repository: ghcr.io/soft-titus/hello
          tag: "1.0.0"
        configMaps:
          env:
            enabled: true
            data:
              LOG_LEVEL: "INFO"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        hpa:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetCPUUtilizationPercentage: 80
          targetMemoryUtilizationPercentage: 75
        service:
          enabled: true
          ports:
            - name: http
              port: 80
              containerPort: 8080
        httpRoute:
          enabled: true
          parentRefs:
            - name: envoy-gateway
              namespace: envoy-gateway-system
          hostnames:
            - hello-hpa.heterodon.local
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /
              backendRefs:
                - name: hello-hpa
                  port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-hpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
