---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  project: hello
  source:
    repoURL: git@github.com:soft-titus/argocd-apps.git
    path: "env/irrawaddy/charts/microservice"
    targetRevision: main
    helm:
      valueFiles:
        - ../../hello/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
