---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-vpa
  namespace: argocd
spec:
  project: hello
  source:
    repoURL: git@github.com:soft-titus/argocd-apps.git
    path: "env/heterodon/charts/microservice"
    targetRevision: main
    helm:
      valueFiles:
        - ../../projects/hello/hello-vpa/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-vpa
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.name=="microservice") | .resources'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
