microservice:
  fullnameOverride: "hello-hpa"
  image:
    repository: ghcr.io/soft-titus/hello
    tag: "0.0.0"
    argocdImageUpdater:
      enabled: true
      applicationNamespace: "argocd"
      applicationNamePattern: "hello-hpa"
      images:
      - alias: app
        imageName: ghcr.io/soft-titus/hello
        commonUpdateSettings:
          updateStrategy: semver
          allowTags: "regexp:^1\\.[0-9]+\\.[0-9]+$"
        manifestTargets:
          helm:
            name: microservice.image.repository
            tag: microservice.image.tag
      writeBackConfig:
        method: git
        gitConfig:
          writeBackTarget: "helmvalues:/env/heterodon/projects/hello/hello-hpa/values.yaml"
  configMaps:
    env:
      enabled: true
      data:
        LOG_LEVEL: "INFO"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 75
  service:
    enabled: true
    ports:
    - name: http
      port: 80
      containerPort: 8080
  httpRoute:
    enabled: true
    parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
    hostnames:
    - hello-hpa.heterodon.local
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: hello-hpa
        port: 80
