---
kind: Kustomization
helmCharts:
  - name: microservice
    version: 0.*
    repo: https://soft-titus.github.io/titus-charts
    releaseName: hello-test
    valuesFile: values.yaml

images:
  - name: ghcr.io/soft-titus/hello
    newTag: "0.0.0"
